# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('son', 'Son'), ('Daughter', 'daughter'), ('mother in law', 'Mother in law'), ('grandfather in law', 'Grand father in law')], default='father', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('main_occupation', models.CharField(choices=[('agriculture', 'Agriculture'), ('foreign employment', 'Foreign Employment')], default='agriculture', max_length=50)),
                ('education', models.CharField(choices=[('slc', 'SLC'), ('inter', 'Inter'), ('bachelor', 'Bachelor'), ('master', 'Master')], default='slc', max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('citizenship_no', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('member_in_past', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3)),
                ('disease', models.CharField(choices=[('no', 'No'), ('Yes', 'Yes')], default='no', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Family Member Information ',
            },
        ),
        migrations.CreateModel(
            name='SpouseCitizenshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship_no', models.CharField(max_length=10, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=20)),
                ('issued_date', models.DateField()),
                ('citizenship_photo', models.ImageField(upload_to='kycform/family_description/spouce_citizenship_photo')),
            ],
            options={
                'verbose_name_plural': 'Spouse Citizenship Information ',
            },
        ),
        migrations.CreateModel(
            name='SpouseDrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_no', models.CharField(max_length=20, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=30)),
                ('issued_date', models.DateField()),
                ('driving_license_photo', models.ImageField(upload_to='kycform/family_description/spouce_driving_license_photo')),
            ],
            options={
                'verbose_name_plural': 'Spouse Driving License Information ',
            },
        ),
        migrations.CreateModel(
            name='SpouseOccoupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('agriculture', 'Agriculture'), ('foreign employment', 'Foreign Employment')], default='agriculture', max_length=100)),
                ('trading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('industry', models.CharField(choices=[('Nepal', 'Nepal')], default='', max_length=50)),
                ('services', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Spouse Occupation Information ',
            },
        ),
        migrations.CreateModel(
            name='SpousePassportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_no', models.CharField(max_length=30, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=50)),
                ('issued_date', models.DateField()),
                ('passport_photo', models.ImageField(upload_to='kycform/family_description/spouce_passport_photo')),
            ],
            options={
                'verbose_name_plural': 'Spouse Passport Information ',
            },
        ),
    ]
