# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('mother', 'Mother'), ('son', 'Son'), ('Daughter', 'daughter'), ('mother in law', 'Mother in law'), ('grandfather in law', 'Grand father in law')], default='father', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('main_occupation', models.CharField(choices=[('agriculture', 'Agriculture'), ('foreign employment', 'Foreign Employment')], default='agriculture', max_length=50)),
                ('education', models.CharField(choices=[('slc', 'SLC'), ('inter', 'Inter'), ('bachelor', 'Bachelor'), ('master', 'Master')], default='slc', max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('citizenship_no', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('member_in_past', models.CharField(choices=[('yes', 'Yes'), ('No', 'no')], default='no', max_length=3)),
                ('diseaase', models.CharField(choices=[('yes', 'Yes'), ('No', 'no')], default='no', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpouseCitizenshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship_no', models.CharField(max_length=10, unique=True)),
                ('issued_from', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Laltipur'), ('gulmi', 'Gulmi')], default='gulmi', max_length=20)),
                ('issued_date', models.DateField()),
                ('citizenship_photo', models.ImageField(upload_to='kycform/family_description/spouce_citizenship_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpouseDrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_no', models.CharField(max_length=20, unique=True)),
                ('issued_from', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Laltipur'), ('gulmi', 'Gulmi')], default='gulmi', max_length=30)),
                ('issued_date', models.DateField()),
                ('driving_license_photo', models.ImageField(upload_to='kycform/family_description/spouce_driving_license_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpouseOccoupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('agriculture', 'Agriculture'), ('foreign employment', 'Foreign Employment')], default='agriculture', max_length=100)),
                ('trading', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('industry', models.CharField(choices=[('Nepal', 'Nepal')], default='', max_length=50)),
                ('services', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpousePassportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_no', models.CharField(max_length=30, unique=True)),
                ('issued_from', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Laltipur'), ('gulmi', 'Gulmi')], default='gulmi', max_length=50)),
                ('issued_date', models.DateField()),
                ('passport_photo', models.ImageField(upload_to='kycform/family_description/spouce_passport_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
