# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydescription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymemberinfo',
            name='diseaase',
        ),
        migrations.AddField(
            model_name='familymemberinfo',
            name='disease',
            field=models.CharField(choices=[('no', 'No'), ('Yes', 'Yes')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='familymemberinfo',
            name='member_in_past',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3),
        ),
    ]
