# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familydescription', '0003_auto_20160401_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymemberinfo',
            options={'verbose_name_plural': 'Family Member Information '},
        ),
        migrations.AlterModelOptions(
            name='spousecitizenshipinfo',
            options={'verbose_name_plural': 'Spouse Citizenship Information '},
        ),
        migrations.AlterModelOptions(
            name='spousedrivinglicense',
            options={'verbose_name_plural': 'Spouse Driving License Information '},
        ),
        migrations.AlterModelOptions(
            name='spouseoccoupation',
            options={'verbose_name_plural': 'Spouse Occupation Information '},
        ),
        migrations.AlterModelOptions(
            name='spousepassportinfo',
            options={'verbose_name_plural': 'Spouse Passport Information '},
        ),
    ]
