# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestock_name', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffaloes'), ('ox', 'OX'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('pig', 'Pig'), ('duck', 'Duck'), ('hen', 'Hen'), ('fowl', 'Fowl'), ('others', 'Others')], default='buffaloes', max_length=100)),
                ('livestock_number', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Livestock Details',
            },
        ),
    ]
