# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_info', models.DateField(auto_now=True)),
                ('branch', models.CharField(choices=[('baneshwor', 'Baneshwor'), ('thimi', 'Thimi'), ('pokhara', 'Pokhara'), ('tamghas', 'Tamghas')], default='baneshwor', max_length=50)),
                ('center_code', models.IntegerField()),
                ('center_name', models.CharField(max_length=100)),
                ('group_code', models.IntegerField()),
                ('member_code', models.IntegerField()),
            ],
            options={
                'ordering': ('center_name',),
            },
        ),
    ]
