# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchinfo',
            options={'ordering': ('center_name',), 'verbose_name': 'Branche'},
        ),
        migrations.AddField(
            model_name='branchinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 10, 50, 39, 476634, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
