# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOnCollateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('particular', models.CharField(max_length=100, verbose_name='Particular name')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_category', models.CharField(choices=[('agriculture', 'Agriculture'), ('industry', 'Industry'), ('trading', 'Trading'), ('services', 'Services')], default='agriculture', max_length=40)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_turn_over', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Average turn over per month')),
                ('doe', models.DateField(verbose_name='Date of Eastblishment')),
                ('vat_no', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Business',
            },
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('electronic_type', models.CharField(choices=[('mobile', 'Mobile'), ('television', 'Television'), ('refrigerator', 'Refrigerator'), ('others', 'Others')], default='mobile', max_length=25)),
                ('total', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('furniture_name', models.CharField(max_length=30)),
                ('no_of_item', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_type', models.CharField(choices=[('borrow', 'Borrow'), ('lend', 'Lend')], default='borrow', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=2)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ornaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomeexpense.Ornament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'motorcycle'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('scooter', 'Scooter'), ('bus', 'Bus'), ('truck', 'Truck'), ('others', 'others')], default='motorcycle', max_length=40)),
                ('total', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
