# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crops',
            options={'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='landdetails',
            options={'verbose_name_plural': 'Land Details'},
        ),
    ]
