# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_name', models.CharField(choices=[('wheat', 'Wheat'), ('paddy', 'Paddy'), ('coffee', 'Coffe'), ('maize', 'Maize'), ('millet', 'Millet'), ('barley', 'Barley'), ('sugercane', 'Sugercane'), ('tobocco', 'Tobacoo'), ('others', 'Others')], default='wheat', max_length=100)),
                ('production_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Crops',
            },
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_category', models.CharField(choices=[('cat1', 'cat1')], default='farming land', max_length=255)),
                ('land_type', models.CharField(choices=[('landtype', 'landtype')], default='others', max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdetail.Crop')),
            ],
            options={
                'verbose_name_plural': 'Land Details',
            },
        ),
        migrations.CreateModel(
            name='LandMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('measured_in', models.CharField(choices=[('square ft', 'Square Ft'), ('bigha', 'Bigha'), ('ropani', 'Ropani'), ('katha', 'Katha'), ('dhur', 'Dhur'), ('aana', 'Aana')], default='ropani', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='landdetail',
            name='land_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdetail.LandMeasurement'),
        ),
    ]
