# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maitiaddress',
            name='district',
            field=models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=100),
        ),
        migrations.AlterField(
            model_name='maitiaddress',
            name='zone',
            field=models.CharField(choices=[('mechi', 'Mechi'), ('koshi', 'Koshi'), ('sagarmatha', 'Sagarmatha'), ('janakpur', 'Janakpur'), ('bagmati', 'Bagmati'), ('narayani', 'Narayani'), ('gandaki', 'Gandaki'), ('dhawalagiri', 'Dhawalagiri'), ('lumbini', 'Lumbini'), ('rapti', 'Rapti'), ('bheri', 'Bheri'), ('karnali', 'Karnali'), ('seti', 'Seti'), ('mahakali', 'Mahakali')], default='Lumbini', max_length=100),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='district',
            field=models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=100),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='zone',
            field=models.CharField(choices=[('mechi', 'Mechi'), ('koshi', 'Koshi'), ('sagarmatha', 'Sagarmatha'), ('janakpur', 'Janakpur'), ('bagmati', 'Bagmati'), ('narayani', 'Narayani'), ('gandaki', 'Gandaki'), ('dhawalagiri', 'Dhawalagiri'), ('lumbini', 'Lumbini'), ('rapti', 'Rapti'), ('bheri', 'Bheri'), ('karnali', 'Karnali'), ('seti', 'Seti'), ('mahakali', 'Mahakali')], default='Lumbini', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryaddress',
            name='district',
            field=models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=100),
        ),
        migrations.AlterField(
            model_name='temporaryaddress',
            name='zone',
            field=models.CharField(choices=[('mechi', 'Mechi'), ('koshi', 'Koshi'), ('sagarmatha', 'Sagarmatha'), ('janakpur', 'Janakpur'), ('bagmati', 'Bagmati'), ('narayani', 'Narayani'), ('gandaki', 'Gandaki'), ('dhawalagiri', 'Dhawalagiri'), ('lumbini', 'Lumbini'), ('rapti', 'Rapti'), ('bheri', 'Bheri'), ('karnali', 'Karnali'), ('seti', 'Seti'), ('mahakali', 'Mahakali')], default='Lumbini', max_length=100),
        ),
    ]
