# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160401_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maitiaddress',
            options={'verbose_name_plural': 'Maiti Address'},
        ),
        migrations.AlterModelOptions(
            name='permanentaddress',
            options={'verbose_name_plural': 'Permanent Address'},
        ),
        migrations.AlterModelOptions(
            name='temporaryaddress',
            options={'verbose_name_plural': 'Temporary Address'},
        ),
    ]
