# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landdetail', '0001_initial'),
        ('familydescription', '0001_initial'),
        ('branch', '0001_initial'),
        ('livestock', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship_no', models.CharField(max_length=10, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=20)),
                ('issued_date', models.DateField()),
                ('citizenship_photo', models.ImageField(upload_to='kycform/citizenship_info/citizenship_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_no', models.CharField(max_length=20, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=30)),
                ('issued_date', models.DateField()),
                ('license_photo', models.ImageField(upload_to='kycform/drivinglicense/license_photo/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general', models.CharField(choices=[('slc', 'SLC'), ('inter', 'Inter'), ('bachelor', 'Bachelor'), ('master', 'Master')], default='slc', max_length=15)),
                ('technical', models.CharField(choices=[('engineering', 'ME/MSC/')], default='engineering', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=50)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=50)),
                ('issued_date', models.DateField()),
                ('bill_photo', models.ImageField(upload_to='kycform/electricitybill/bill_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarriageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_no', models.CharField(max_length=30)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=30)),
                ('issued_date', models.DateField()),
                ('marriage_certificate_photo', models.ImageField(upload_to='kycform/marriage_certificate/marriage_certificate_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport_no', models.CharField(max_length=30, unique=True)),
                ('issued_from', models.CharField(choices=[('taplegung', 'Taplegung'), ('panchathar', 'Panchathar'), ('ilam', 'Ilam'), ('jhapa', 'Jhapa'), ('moranga', 'Moranga'), ('sunsari', 'Sunsari'), ('dhankuta', 'Dhankuta'), ('tehrathum', 'Tehrathum'), ('shankhuwasabha', 'Shankhuwasabha'), ('bhojpur', 'Bhojpur'), ('solukhumbu', 'Solukhumbu'), ('okhaldhunga', 'Okhaldhunga'), ('khotang', 'Khotang'), ('udaypur', 'Udaypur'), ('saptari', 'Saptari'), ('sirha', 'Sirha'), ('dhanusha', 'Dhanusha'), ('mahotari', 'Mahotari'), ('sarlahi', 'Sarlahi'), ('sindhuli', 'Sindhuli'), ('ramechhap', 'Ramechhap'), ('dholakha', 'Dholakha'), ('sindhuplananchok', 'Sindhuplananchok'), ('kabhreplanchok', 'Kabhreplanchok'), ('lalitpur', 'Lalitpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('nuwakot', 'Nuwakot'), ('rashuwa', 'Rashuwa'), ('dhading', 'Dhading'), ('makawanpur', 'Makawanpur'), ('rautahat', 'Rautahat'), ('bara', 'Bara'), ('parsa', 'Parsa'), ('chitawan', 'Chitawan'), ('ghorakha', 'Ghorakha'), ('lamjung', 'Lamjung'), ('tanahnu', 'Tanahnu'), ('syanja', 'Syanja'), ('kaski', 'Kaski'), ('manang', 'Manang'), ('mustang', 'Mustang'), ('myagdi', 'Myagdi'), ('parbat', 'Parbat'), ('paglung', 'Baglung'), ('gulmi', 'Gulmi'), ('palpa', 'Palpa'), ('nawalparasi', 'Nawalparasi'), ('rupandehi', 'Rupandehi'), ('kapilbasthu', 'Kapilbasthu'), ('arghakhanchi', 'Arghakhanchi'), ('pyuthan', 'Pyuthan'), ('rolpa', 'Rolpa'), ('rukum', 'Rukum'), ('salyan', 'Salyan'), ('dang', 'Dang'), ('banke', 'Banke'), ('bardiya', 'Bardiya'), ('shurkhet', 'Shurkhet'), ('dailekha', 'Dailekha'), ('jajarkot', 'Jajarkot'), ('dolpa', 'Dolpa'), ('jumla', 'Jumla'), ('kalikot', 'Kalikot'), ('mugu', 'Mugu'), ('humla', 'Humla'), ('bajura', 'Bajura'), ('bajhanga', 'Bajhanga'), ('aachham', 'Aachham'), ('doti', 'Doti'), ('kailali', 'Kailali'), ('kanchanpur', 'Kanchanpur'), ('dadeldhura', 'Dadeldhura'), ('baitadi', 'Baitadi'), ('darchula', 'Darchula')], default='gulmi', max_length=50)),
                ('issued_date', models.DateField()),
                ('passport_photo', models.ImageField(upload_to='kycform/passport/passport_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('husband_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_in_law_name', models.CharField(blank=True, max_length=100)),
                ('grand_father_in_law_name', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(choices=[('husband', 'Husband'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother')], default='husband', max_length=7)),
                ('dob', models.DateField(auto_now=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='female', max_length=6)),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('widow', 'Widow')], default='married', max_length=9)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('islam', 'Islam'), ('buddhist', 'Buddhist'), ('christian', 'Christian'), ('others', 'Others')], default='hindu', max_length=10)),
                ('ethnic_group', models.CharField(choices=[('brahmin', 'Brahmin')], default='Brahmin', max_length=20)),
                ('caste', models.CharField(choices=[('brahmin', 'Brahmin'), ('sudra', 'Sudra')], default='brahmin', max_length=20)),
                ('nationality', models.CharField(choices=[('nepali', 'Nepali')], default='nepali', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('finger_print', models.ImageField(upload_to='kycform/personal_info/finger_print')),
                ('signature', models.ImageField(upload_to='kycform/personal_info/signature')),
                ('medication', models.BooleanField()),
                ('childrens', models.IntegerField(default=0)),
                ('boys', models.IntegerField(default=0)),
                ('girls', models.IntegerField(default=0)),
                ('other_banks', models.CharField(choices=[('bank', 'Bank'), ('micro-finance', 'Micro-Finance'), ('co-operative', 'co-operative')], default='bank', max_length=50)),
                ('family_type', models.CharField(choices=[('joint', 'Joint'), ('nuclear', 'Nuclear')], default='joint', max_length=7)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.BranchInfo')),
                ('citizenship_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.CitizenshipInfo')),
                ('driving_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.DrivingLicense')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.Education')),
                ('electricity_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kycform_personalinfos', to='kycform.ElectricityBill')),
                ('family_member_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydescription.FamilyMemberInfo')),
                ('land_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdetail.LandDetail')),
                ('livestock_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockDetail')),
                ('maiti_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.MaitiAddress')),
                ('marriage_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.MarriageCertificate')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.Passport')),
                ('permanent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.PermanentAddress')),
                ('spouse_citizenship_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseCitizenshipInfo')),
                ('spouse_driving_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseDrivingLicense')),
                ('spouse_occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseOccoupation')),
                ('spouse_passport_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpousePassportInfo')),
                ('temporary_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.TemporaryAddress')),
            ],
            options={
                'ordering': ('first_name',),
                'verbose_name_plural': 'Personal Infromation',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institue_name', models.CharField(max_length=100)),
                ('training_name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=30)),
                ('certificate', models.ImageField(upload_to='kycform/training/certificate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.Training'),
        ),
    ]
