# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('kycform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='maiti_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='address.MaitiAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='permanent_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.PermanentAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='temporary_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.TemporaryAddress'),
            preserve_default=False,
        ),
    ]
