# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('kycform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship_no', models.CharField(max_length=10, unique=True)),
                ('issued_from', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('lalitpur', 'Laltipur'), ('gulmi', 'Gulmi')], default='gulmi', max_length=20)),
                ('issued_date', models.DateField()),
                ('citizenship_photo', models.ImageField(upload_to='kycform/citizenship_info/citizenship_photo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='citizenship_photo',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='issued_from',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='member_registration_date',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='maiti_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='address.MaitiAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='permanent_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='address.PermanentAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='temporary_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='address.TemporaryAddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='citizenship_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kycform.CitizenshipInfo'),
        ),
    ]
