# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydescription', '0001_initial'),
        ('kycform', '0002_auto_20160331_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='boys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='childrens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='family_member_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familydescription.FamilyMemberInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='family_type',
            field=models.CharField(choices=[('joint', 'Joint'), ('nuclear', 'Nuclear')], default='joint', max_length=7),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='girls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='spouse_citizenship_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseCitizenshipInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='spouse_driving_license',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseDrivingLicense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='spouse_occupation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpouseOccoupation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='spouse_passport_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familydescription.SpousePassportInfo'),
            preserve_default=False,
        ),
    ]
