# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0003_auto_20160331_1447'),
        ('kycform', '0002_auto_20160331_1514'),
    ]

    operations = [
    ]
