# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycform', '0003_auto_20160401_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='father_in_law_name',
            field=models.CharField(max_length=100),
        ),
    ]
