# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
        ('kycform', '0005_auto_20160401_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ('first_name',), 'verbose_name_plural': 'Personal Infromation'},
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='livestock_details',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStockDetails'),
            preserve_default=False,
        ),
    ]
