# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_type', models.CharField(choices=[('pakki', 'Pakki'), ('kachi', 'Kachi'), ('kath', 'Kath'), ('bans', 'Bans'), ('fuss', 'Fuss'), ('others', 'Others')], default='kachi', max_length=20)),
                ('no_of_houses', models.IntegerField(default=0)),
                ('house_covered_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Covered Area in km')),
                ('roof_of_house', models.CharField(choices=[('tile', 'Tile'), ('tin', 'Tin'), ('cemented', 'Cemented'), ('bush', 'Bush'), ('others', 'Others')], default='tile', max_length=20, verbose_name='Roof type')),
                ('no_of_rooms', models.IntegerField()),
                ('material_used', models.CharField(choices=[('brick', 'Brick'), ('bamboo', 'Bamboo'), ('stone', 'Stone'), ('clay', 'Clay'), ('others', 'Others')], default='brick', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'House Details',
            },
        ),
    ]
